name: Snake Game

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate snake
        uses: Platane/snk@v2
        with:
          # GitHub token to authenticate and access the repository
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snake GIF
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: snake.gif

      - name: Update README with snake GIF
        run: |
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"content\": \"$(base64 snake.gif)\"}" \
          "https://api.github.com/repos/${{ github.repository }}/contents/snake.svg"
