name: Generate Snake Animation

on:
  schedule:
    - cron: "* */12 * * *" # Run every 12 hours
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
    - main # Adjust if your main branch has a different name

jobs:
  generate:
    permissions:
      contents: write # Ensure permissions are set to write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # Adjust if needed
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
